name: hana_in_docker

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: :$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

#     - name: downcase REPO
#       run: | 
#         echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }} .
    - name: push image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
